# Generated by Django 4.1.3 on 2022-12-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cpassword',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
